# Generated by Django 4.1 on 2023-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categor',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subplaces',
            name='districts',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='title',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='state',
        ),
        migrations.AddField(
            model_name='person',
            name='account',
            field=models.CharField(choices=[('S', 'savings'), ('C', 'current')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='material',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=2, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='place',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='subplaces',
        ),
    ]
