# Generated by Django 4.1 on 2023-01-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_rename_country_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
